Rename, Study: 커피샵 예제를 통한 상속 이해
jvmoverloads/java-coordinate-calculator-chs4413 pull request #1
Opened 2023-05-06 02:54 UTC by chs1234

2023-05-06 03:01 UTC, dongKos requested changes
고생하셨습니다! 코멘트 확인 부탁드려요 :)

2023-05-06 03:01 UTC, dongKos commented on src/main/java/coffee/after/CaffeinBeverage.java
> +    void prepareRecipe() {
요런메소드를 template method라고 합니다. 디자인 구루에서 찾아보시면 좋을 것 같아요!

2023-05-06 03:01 UTC, dongKos commented on src/main/java/coffee/after/Coffee.java
> +    void brew() {
여기엔 어떤 접근 제한자를 추가하면 좋을까요?

2023-05-06 03:01 UTC, dongKos commented on src/main/java/coffee/after/Main.java
> +    public static void main(String[] args) {
요걸 테스트로 검증해보면 어떨까요?

2023-05-09 01:57 UTC, chs1234 commented on src/main/java/coffee/after/CaffeinBeverage.java
> +    void prepareRecipe() {
해당 리뷰는 바로 반영하여 올렸었는데, 다시 한번 확인해주세요~!

(+ 연료주입 pr이 머지되어 해당 브랜치에 코드가 머지되었습니다!)

2023-05-09 14:43 UTC, dongKos commented
@chs1234 
리뷰가 반영 안된것 같은데 어떤걸 확인하면 될까요?

2023-05-09 14:55 UTC, chs1234 reviewed
@dongKos 
다시 한번 확인부탁해요~

2023-05-09 14:55 UTC, chs1234 commented on src/main/java/coffee/after/Coffee.java
>          System.out.println("필터를 활용해 커피를 내린다.");
`protected` 접근제한자 추가하였습니다!

2023-05-09 14:55 UTC, chs1234 commented on src/test/java/BeverageTest.java
> +
테스트 코드도 추가했습니다.!

2023-05-09 14:55 UTC, chs1234 commented on src/main/java/coffee/after/Tea.java
>          System.out.println("티백을 담근다.");
Coffee와 동일하게 Tea 객체도 `protected` 적용.!

2023-05-09 14:57 UTC, dongKos approved these changes
LGTM 👍

2023-05-09 15:24 UTC, merged